title: Economics Ph.D. App. Deadlines
description: Github Page showing application deadlines of Economics Ph.D. programmes. MIT licensed.
google_analytics: UA-85626326-1

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false

theme: jekyll-theme-slate
